version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: tpe-project-postgres
    environment:
      POSTGRES_USER: estudante
      POSTGRES_PASSWORD: ifsp
      POSTGRES_DB: tpe-database
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tpe-project-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: ifsp
    ports:
      - 8080:80
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin: