version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: tpe-project-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: estudante
      POSTGRES_PASSWORD: ifsp
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tpe-project-pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: ifsp
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: